
CREATE TABLE [dbo].[v61TableDef](
	[TABLE_NAME] NVARCHAR(100) ,
	[COLUMN_NAME] NVARCHAR(100) ,
	[DATA_TYPE]  NVARCHAR(100) ,
	[CHARACTER_MAXIMUM_LENGTH] INT ,
	[NUMERIC_PRECISION] INT ,
	[NUMERIC_SCALE] INT
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[v61Tables](
	[TABLE_NAME]  NVARCHAR(100) 
) ON [PRIMARY]
GO
