
CREATE TABLE [dbo].TableKeyFields(
	[TABLE_NAME] NVARCHAR(100) ,
	[KEY_COLUMN]  NVARCHAR(100)  ,
	[LEADING_ZERO_REQUIRED] BIT	
) ON [PRIMARY]

GO

INSERT INTO TableKeyFields(TABLE_NAME, [KEY_COLUMN],[LEADING_ZERO_REQUIRED]) VALUES ('ArCustomer','Customer',1)
